# Generated by Django 6.1.1 on 2026-09-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='dealer',
        ),
        migrations.AddField(
            model_name='review',
            name='dealer_id',
            field=models.IntegerField(default=0),
        ),
    ]
